"""empty message

Revision ID: 2575f6a8cc24
Revises: c843fd0d7846
Create Date: 2023-04-13 09:48:55.648365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2575f6a8cc24'
down_revision = 'c843fd0d7846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handle', sa.String(length=64), nullable=False))
        batch_op.drop_index('ix_institute_title')
        batch_op.create_index(batch_op.f('ix_institute_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_institute_handle'), ['handle'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('institute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institute_handle'))
        batch_op.drop_index(batch_op.f('ix_institute_title'))
        batch_op.create_index('ix_institute_title', ['title'], unique=False)
        batch_op.drop_column('handle')

    # ### end Alembic commands ###
