"""empty message

Revision ID: 7e5dbcadc154
Revises: 2575f6a8cc24
Create Date: 2023-04-13 18:05:04.292455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5dbcadc154'
down_revision = '2575f6a8cc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.drop_column('hospital')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital', sa.VARCHAR(length=128), nullable=False))

    # ### end Alembic commands ###
