"""empty message

Revision ID: 8bb078d2cb4b
Revises: c2a6aa3c56a8
Create Date: 2023-04-13 21:37:59.879753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb078d2cb4b'
down_revision = 'c2a6aa3c56a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
