"""empty message

Revision ID: bde6fe600265
Revises: 8bb078d2cb4b
Create Date: 2023-04-14 18:10:51.844661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde6fe600265'
down_revision = '8bb078d2cb4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institute', schema=None) as batch_op:
        batch_op.drop_index('ix_institute_handle')
        batch_op.create_index(batch_op.f('ix_institute_handle'), ['handle'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index('ix_user_email', ['email'], unique=False)

    with op.batch_alter_table('institute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institute_handle'))
        batch_op.create_index('ix_institute_handle', ['handle'], unique=False)

    # ### end Alembic commands ###
