"""empty message

Revision ID: c843fd0d7846
Revises: 8e26c6117577
Create Date: 2023-04-12 21:11:43.619924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c843fd0d7846'
down_revision = '8e26c6117577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inmate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name=op.f('fk_inmate_id_user')),
    sa.ForeignKeyConstraint(['institute'], ['institute.id'], name=op.f('fk_inmate_institute_institute')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inmate'))
    )
    op.create_table('professional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name=op.f('fk_professional_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professional'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('user_type', sa.String(length=128), nullable=False))
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_unique_constraint('uq_user_username', ['username'])
        batch_op.drop_column('user_type')
        batch_op.drop_column('password_hash')

    op.drop_table('professional')
    op.drop_table('inmate')
    # ### end Alembic commands ###
