"""empty message

Revision ID: d1cb6eeef066
Revises: bde6fe600265
Create Date: 2023-04-15 19:11:13.992136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cb6eeef066'
down_revision = 'bde6fe600265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('reviewer', sa.String(length=50), nullable=True),
    sa.Column('professional', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name=op.f('fk_review_id_user')),
    sa.ForeignKeyConstraint(['professional'], ['professional.id'], name=op.f('fk_review_professional_professional')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
